# Generated by Django 4.1.7 on 2023-03-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enlace', models.URLField()),
                ('temporada', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=20)),
                ('ultimo_club', models.CharField(max_length=100)),
                ('nuevo_club', models.CharField(max_length=100)),
                ('valor_mercado', models.CharField(max_length=20)),
                ('coste', models.CharField(max_length=20)),
            ],
        ),
    ]
