# Generated by Django 4.1.7 on 2023-03-16 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_importacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
